--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-08-03 18:05:17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 35134)
-- Name: case; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."case" (
    closed_at date,
    fine_amount numeric(7,2) NOT NULL,
    id_driver integer NOT NULL,
    numbercase integer NOT NULL,
    overdue_count integer NOT NULL,
    user_id integer,
    violation_date date NOT NULL,
    plate_number character varying(10) NOT NULL,
    address character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT case_overdue_count_check CHECK (((overdue_count <= 2) AND (overdue_count >= 0)))
);


--
-- TOC entry 217 (class 1259 OID 35133)
-- Name: case_numbercase_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."case" ALTER COLUMN numbercase ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.case_numbercase_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 35144)
-- Name: contact; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact (
    id_message integer NOT NULL,
    numbercase integer NOT NULL,
    contact_date timestamp(6) without time zone NOT NULL,
    contact_type character varying(255) NOT NULL,
    result character varying(255) NOT NULL,
    CONSTRAINT contact_contact_type_check CHECK (((contact_type)::text = ANY ((ARRAY['EMAIL'::character varying, 'PHONE'::character varying, 'LETTER'::character varying])::text[])))
);


--
-- TOC entry 219 (class 1259 OID 35143)
-- Name: contact_id_message_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact ALTER COLUMN id_message ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_id_message_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 35153)
-- Name: driver; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.driver (
    birth_date date NOT NULL,
    id_driver integer NOT NULL,
    phone character varying(9),
    pesel character varying(11),
    passport_number character varying(14) NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    address character varying(255),
    email character varying(255),
    notes oid NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 35152)
-- Name: driver_id_driver_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.driver ALTER COLUMN id_driver ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_id_driver_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 35167)
-- Name: file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file (
    file_id integer NOT NULL,
    numbercase integer,
    uploaded_at date NOT NULL,
    file_path character varying(500) NOT NULL,
    file_type character varying(255) NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT file_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['PHOTOGRAPH_OF_INCIDENT'::character varying, 'PAYMENT_DEMAND_NOTICE'::character varying, 'PRE_LITIGATION_PAYMENT_DEMAND'::character varying, 'NOTICE_OF_CASE_REFERRAL_TO_COURT'::character varying, 'PAYMENT_CONFIRMATION'::character varying, 'OFFICIAL_NOTE'::character varying, 'CLIENT_CONTACT_REPORT'::character varying, 'MAIL_LABELS'::character varying])::text[])))
);


--
-- TOC entry 223 (class 1259 OID 35166)
-- Name: file_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.file ALTER COLUMN file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 35176)
-- Name: report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report (
    generated_at date NOT NULL,
    generated_by integer NOT NULL,
    report_id integer NOT NULL,
    file_path character varying(500) NOT NULL,
    report_type character varying(255) NOT NULL,
    CONSTRAINT report_report_type_check CHECK (((report_type)::text = ANY ((ARRAY['FINANCIAL_REPORT'::character varying, 'CASE_STATUS_REPORT'::character varying, 'EMPLOYEE_PERFORMANCE_REPORT'::character varying, 'MONTHLY_SUMMARY'::character varying, 'COURT_REPORT'::character varying])::text[])))
);


--
-- TOC entry 225 (class 1259 OID 35175)
-- Name: report_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 35185)
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    user_id integer NOT NULL,
    phone character varying(9) NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'EMPLOYEE'::character varying, 'ACCOUNTANT'::character varying])::text[])))
);


--
-- TOC entry 227 (class 1259 OID 35184)
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 35195)
-- Name: vehicle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehicle (
    id_driver integer NOT NULL,
    plate_number character varying(10) NOT NULL,
    brand character varying(50) NOT NULL,
    color character varying(50) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- TOC entry 4863 (class 2613 OID 35235)
-- Name: 35235..43451; Type: BLOB METADATA; Schema: -; Owner: -
--

SELECT pg_catalog.lo_create('35235');
SELECT pg_catalog.lo_create('35236');
SELECT pg_catalog.lo_create('35237');
SELECT pg_catalog.lo_create('35238');
SELECT pg_catalog.lo_create('35239');
SELECT pg_catalog.lo_create('35240');
SELECT pg_catalog.lo_create('35241');
SELECT pg_catalog.lo_create('35242');
SELECT pg_catalog.lo_create('35243');
SELECT pg_catalog.lo_create('35244');
SELECT pg_catalog.lo_create('35246');
SELECT pg_catalog.lo_create('35247');
SELECT pg_catalog.lo_create('35248');
SELECT pg_catalog.lo_create('35249');
SELECT pg_catalog.lo_create('35250');
SELECT pg_catalog.lo_create('35251');
SELECT pg_catalog.lo_create('35252');
SELECT pg_catalog.lo_create('35253');
SELECT pg_catalog.lo_create('35254');
SELECT pg_catalog.lo_create('35255');
SELECT pg_catalog.lo_create('43449');
SELECT pg_catalog.lo_create('43450');
SELECT pg_catalog.lo_create('43451');

--
-- TOC entry 4851 (class 0 OID 35134)
-- Dependencies: 218
-- Data for Name: case; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 250.00, 4, 36, 0, 9, '2026-06-10', 'KR77889', 'test', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 1.00, 1, 40, 0, NULL, '2026-06-18', 'PO6677A', 'ASDsAD', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 1.00, 1, 41, 0, NULL, '2026-06-18', 'PO6677A', 'ASDsAD', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 1.00, 1, 42, 0, NULL, '2026-06-18', 'PO6677A', 'ASDsAD', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 100.00, 12, 43, 0, NULL, '2026-06-18', 'PO6677A', 'ASDsAD', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 250.00, 19, 44, 0, NULL, '2026-06-01', 'WI34567', 'ul. Marszałkowska 100, Warszawa', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 250.00, 19, 45, 0, NULL, '2026-06-01', 'WI34567', 'ul. Marszałkowska 100, Warszawa', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 1500.00, 5, 7, 0, 10, '2026-04-28', 'GD9900A', 'Gdańsk, Tunel pod Martwą Wisłą', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 400.00, 6, 8, 0, 10, '2026-05-01', 'DW5544X', 'Wrocław, ul. Legnicka', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 1200.00, 14, 24, 0, 10, '2026-05-07', 'WI9999X', 'S7 Expressway, Radom', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 800.00, 14, 25, 0, 10, '2026-05-08', 'WI9999X', 'Poznań, ul. Głogowska', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 350.00, 14, 26, 0, 10, '2026-05-09', 'WI9999X', 'Łódź, ul. Piotrkowska', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 150.00, 15, 27, 0, 10, '2026-05-10', 'PO7766X', 'Szczecin, ul. Portowa', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 900.00, 16, 32, 0, 10, '2026-05-15', 'DW555AA', 'Lublin, ul. Lipowa', 'IN_PROGRESS');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 500.00, 12, 18, 0, NULL, '2026-05-01', 'W0PUDZIO', 'A2 Highway, Łódź', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 500.00, 15, 28, 0, 9, '2026-05-11', 'PO7766X', 'A1 Highway, Toruń', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES ('2026-05-28', 200.00, 7, 9, 0, 11, '2026-05-05', 'PO6677A', 'Poznań, ul. Głogowska', 'ARCHIVED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 300.00, 4, 6, 0, 11, '2026-05-15', 'KR11223', 'A4 Highway, Katowice', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 400.00, 20, 39, 0, 9, '2026-06-28', 'WY78901', 'Al. Jerozolimskie 45, Warszawa', 'IN_PROGRESS');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 250.00, 3, 3, 0, 10, '2026-05-10', 'WI12345', 'A2 Highway, 104 km, Poznań', 'CLOSED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 300.00, 12, 20, 0, NULL, '2026-05-03', 'W0PUDZIO', 'Kraków, ul. Dietla', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 150.00, 9, 11, 0, 9, '2026-05-11', 'EL88997', 'Łódź, ul. Piotrkowska', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 250.00, 12, 19, 0, NULL, '2026-05-02', 'W0PUDZIO', 'Warszawa, ul. Belwederska', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 500.00, 3, 4, 0, 10, '2026-05-12', 'WI12345', 'Warszawa, Aleje Jerozolimskie 45', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 110.00, 4, 35, 0, 9, '2026-06-28', 'KR77889', 'ASdasdas', 'IN_PROGRESS');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 400.00, 13, 21, 0, NULL, '2026-05-04', 'KR1122A', 'Gdańsk, Al. Grunwaldzka', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES ('2026-05-23', 800.00, 8, 10, 0, 9, '2026-05-08', 'WR1200C', 'S7 Expressway, blisko Radomia', 'ARCHIVED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 150.00, 13, 22, 0, NULL, '2026-05-05', 'KR1122A', 'Wrocław, Rynek', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 450.00, 16, 31, 0, 9, '2026-05-14', 'DW555AA', 'S8 Expressway, Syców', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 200.00, 15, 29, 0, 9, '2026-05-12', 'PO7766X', 'Gdynia, Skwer Kościuszki', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 600.00, 13, 23, 0, 9, '2026-05-06', 'KR1122A', 'A4 Highway, Opole', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 300.00, 16, 30, 0, 9, '2026-05-13', 'DW555AA', 'Katowice, ul. Korfantego', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 100.00, 9, 33, 0, NULL, '2026-06-04', 'EL88997', 'A4', 'REGISTERED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES ('2026-06-24', 603.00, 10, 12, 0, 9, '2026-05-16', 'BI4433C', 'S8 Expressway, Białystok', 'CLOSED');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 100.00, 4, 5, 0, 10, '2026-05-14', 'KR77889', 'Kraków, ul. Floriańska 10', 'WAITING_FOR_CONTACT');
INSERT INTO public."case" (closed_at, fine_amount, id_driver, numbercase, overdue_count, user_id, violation_date, plate_number, address, status) VALUES (NULL, 250.00, 19, 38, 0, NULL, '2026-06-28', 'WI34567', 'ul. Marszałkowska 100, Warszawa', 'REGISTERED');


--
-- TOC entry 4853 (class 0 OID 35144)
-- Dependencies: 220
-- Data for Name: contact; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (1, 32, '2026-05-28 11:23:46.338834', 'EMAIL', 's');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (2, 32, '2026-05-28 11:28:39.824495', 'LETTER', 'ф');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (3, 32, '2026-05-28 11:30:16.246434', 'EMAIL', 'Test');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (4, 32, '2026-05-28 12:06:55.330985', 'EMAIL', 'sdfdsf');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (5, 7, '2026-06-18 17:42:22.032851', 'EMAIL', 'as');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (6, 5, '2026-06-18 17:43:19.767348', 'EMAIL', 'k');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (7, 5, '2026-06-18 17:58:11.171718', 'EMAIL', 'q');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (8, 12, '2026-06-21 16:20:49.012882', 'PHONE', 'as');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (9, 12, '2026-06-21 16:22:47.028014', 'LETTER', 'test');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (10, 12, '2026-06-21 17:06:47.43759', 'PHONE', 'Additional penalty applied: 2.00 PLN. Reason: Late payment');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (11, 12, '2026-06-21 17:08:22.213826', 'PHONE', 'Additional penalty applied: 1.00 PLN. Reason: as');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (12, 35, '2026-06-29 04:24:49.782192', 'PHONE', 'фыв');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (13, 39, '2026-06-29 04:47:50.804954', 'PHONE', 'a');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (14, 35, '2026-06-29 04:48:07.516114', 'PHONE', 'Additional penalty applied: 5.00 PLN. Reason: Late payment');
INSERT INTO public.contact (id_message, numbercase, contact_date, contact_type, result) VALUES (15, 35, '2026-06-29 04:54:01.300403', 'PHONE', 'Additional penalty applied: 5.00 PLN. Reason: Late payment');


--
-- TOC entry 4855 (class 0 OID 35153)
-- Dependencies: 222
-- Data for Name: driver; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('2000-01-20', 1, '000000000', '', 'XYZ1234', 'Test', 'Test', NULL, 'test@test.pl', 35235);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('2024-01-23', 2, '000000000', '1234123414', 'XYZ2123', 'LastTest', 'LastTest', NULL, 'lastexample@gmail.com', 35236);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1985-05-12', 3, '501234567', '85051212345', 'A1B234567', 'Jan', 'Kowalski', NULL, 'jan.kowalski@gmail.com', 35237);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1992-09-23', 4, '602345678', '92092354321', 'CD9876543', 'Anna', 'Nowak', NULL, 'anna.nowak@yahoo.com', 35238);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1978-11-02', 5, '703456789', '78110298765', 'EX1122334', 'Piotr', 'Wiśniewski', NULL, 'piotr.wisnia@gmail.com', 35239);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1988-02-14', 6, '804567890', '88021411223', 'FX4455667', 'Katarzyna', 'Wójcik', NULL, 'kasia.wojcik@outlook.com', 35240);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1995-07-07', 7, '905678901', '95070733445', 'GZ9988776', 'Tomasz', 'Mazur', NULL, 'tomasz.mazur@infomail.pl', 35241);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1983-12-30', 8, '509876543', '83123044556', 'HX5566771', 'Michał', 'Krawczyk', NULL, 'm.krawczyk@gmail.com', 35242);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1991-03-18', 9, '601112233', '91031855667', 'JX4433221', 'Agnieszka', 'Zielińska', NULL, 'aga.zielinska@onet.pl', 35243);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1977-02-07', 12, '601111222', NULL, 'PAS882211', 'Mariusz', 'Pudzianowski', NULL, NULL, 35246);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1963-08-12', 13, '602222333', NULL, 'KPT443322', 'Robert', 'Makłowicz', NULL, NULL, 35247);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1946-09-08', 14, '603333444', NULL, 'ZAL990011', 'Krzysztof', 'Krawczyk', NULL, NULL, 35248);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1987-02-07', 16, '605555669', '80062577881', 'SND554433', 'Monika', 'Brodka', 'ul. Kowalskiego 15', 'monika@gmail.com', 35253);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1980-06-25', 10, '702223344', '80062577889', 'KX9900112', 'Paweł', 'Szymański', 'Asdasd', 'pawel.szym@gmail.com', 35255);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1995-01-02', 19, '501234567', '95010203456', 'APA987654', 'Piotr', 'Nowak', NULL, 'piotr.nowak@gmail.com', 43449);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1998-05-12', 20, '602345678', '98051207890', 'A20260629', 'Anna', 'Kowalska', NULL, 'anna.kowalska@yahoo.com', 43450);
INSERT INTO public.driver (birth_date, id_driver, phone, pesel, passport_number, name, surname, address, email, notes) VALUES ('1970-01-01', 15, '604444555', NULL, 'NOS112233', 'Janusz', 'Polak', NULL, NULL, 43451);


--
-- TOC entry 4857 (class 0 OID 35167)
-- Dependencies: 224
-- Data for Name: file; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (1, 29, '2026-06-24', '/uploads/generated/29_payment_demand_notice_1782252068352.pdf', 'PAYMENT_DEMAND_NOTICE', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (2, 29, '2026-06-24', '/uploads/generated/29_pre_litigation_payment_demand_1782252077465.pdf', 'PRE_LITIGATION_PAYMENT_DEMAND', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (3, 11, '2026-06-24', '/uploads/generated/11_notice_of_case_referral_to_court_1782252149440.pdf', 'NOTICE_OF_CASE_REFERRAL_TO_COURT', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (4, NULL, '2026-06-24', '/uploads/generated/user_9_official_note_1782252159791.pdf', 'OFFICIAL_NOTE', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (5, NULL, '2026-06-24', '/uploads/generated/user_9_client_contact_report_1782252169807.pdf', 'CLIENT_CONTACT_REPORT', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (6, NULL, '2026-06-24', '/uploads/payments/null_payment_1782301340143_payment_test.csv', 'PAYMENT_CONFIRMATION', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (7, 12, '2026-06-24', '/uploads/payments/12_payment_1782302814821_payment_test.csv', 'PAYMENT_CONFIRMATION', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (8, 12, '2026-06-24', '/uploads/photos/photo_2.jpg', 'PHOTOGRAPH_OF_INCIDENT', 9);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (9, 35, '2026-06-29', '/uploads/photos/93ca5734-91f2-4072-958c-b556f01e8be1.jpg', 'PHOTOGRAPH_OF_INCIDENT', 8);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (11, 38, '2026-06-29', '/uploads/photos/photo_34.jpg', 'PHOTOGRAPH_OF_INCIDENT', 8);
INSERT INTO public.file (file_id, numbercase, uploaded_at, file_path, file_type, user_id) VALUES (12, 39, '2026-06-29', '/uploads/photos/photo_35.jpg', 'PHOTOGRAPH_OF_INCIDENT', 8);


--
-- TOC entry 4859 (class 0 OID 35176)
-- Dependencies: 226
-- Data for Name: report; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4861 (class 0 OID 35185)
-- Dependencies: 228
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (7, '501111222', 'Robert', 'Lewandowski', 'robert.admin@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'ADMIN', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (8, '502222333', 'Marta', 'Kowalska', 'marta.admin@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'ADMIN', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (9, '601222333', 'Janusz', 'Nosacz', 'janusz.worker@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'EMPLOYEE', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (10, '602333444', 'Mateusz', 'Borek', 'mateusz.worker@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'EMPLOYEE', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (11, '603444555', 'Karolina', 'Malinowska', 'karolina.worker@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'EMPLOYEE', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (13, '701333444', 'Adam', 'Glapiński', 'adam.cash@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'ACCOUNTANT', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (14, '702444555', 'Beata', 'Szydło', 'beata.cash@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'ACCOUNTANT', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (15, '703555666', 'Mariusz', 'Max', 'mariusz.cash@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'ACCOUNTANT', true);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (16, '704666777', 'Monika', 'Olewnik', 'monika.cash@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'ACCOUNTANT', false);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (12, '604555666', 'Sylwester', 'Wardega', 'sylwester.worker@office.pl', '$2a$10$TJRmUPl.UvRWf7Enl868C./yx8XPi1NXXHO0flamm.G0f5tZDDZZG', 'EMPLOYEE', false);
INSERT INTO public."user" (user_id, phone, name, surname, email, password, role, is_active) VALUES (1, '000000001', 'Admin', 'Admin', 'admin@admin.pl', '$2a$10$ID9vcOJQtgHFMjSgYqoCq.AckchapUGgb8oAnNW6AGVhnijf5Ib06', 'ADMIN', true);


--
-- TOC entry 4862 (class 0 OID 35195)
-- Dependencies: 229
-- Data for Name: vehicle; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (3, 'WI12345', 'Skoda', 'Silver', 'Octavia');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (4, 'KR77889', 'Toyota', 'Red', 'Yaris');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (4, 'KR11223', 'Skoda', 'White', 'Fabia');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (5, 'GD9900A', 'Audi', 'Black', 'A6');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (6, 'DW5544X', 'Volkswagen', 'Blue', 'Golf');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (7, 'PO6677A', 'Ford', 'Grey', 'Focus');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (8, 'WR1200C', 'BMW', 'Dark Blue', '3 Series');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (9, 'EL88997', 'Kia', 'Orange', 'Ceed');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (10, 'BI4433C', 'Hyundai', 'Green', 'Tucson');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (12, 'W0PUDZIO', 'Mercedes', 'Black', 'S-Class');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (13, 'KR1122A', 'Fiat', 'Silver', 'Multipla');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (14, 'WI9999X', 'Porsche', 'White', 'Panamera');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (15, 'PO7766X', 'Volkswagen', 'Green', 'Passat');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (16, 'DW555AA', 'Volkswagen', 'Red', 'Golf');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (19, 'WI34567', 'Toyota', 'Silver', 'Yaris');
INSERT INTO public.vehicle (id_driver, plate_number, brand, color, model) VALUES (20, 'WY78901', 'Volkswagen', 'Blue', 'Golf');


--
-- TOC entry 4870 (class 0 OID 0)
-- Dependencies: 217
-- Name: case_numbercase_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.case_numbercase_seq', 45, true);


--
-- TOC entry 4871 (class 0 OID 0)
-- Dependencies: 219
-- Name: contact_id_message_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contact_id_message_seq', 15, true);


--
-- TOC entry 4872 (class 0 OID 0)
-- Dependencies: 221
-- Name: driver_id_driver_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.driver_id_driver_seq', 20, true);


--
-- TOC entry 4873 (class 0 OID 0)
-- Dependencies: 223
-- Name: file_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.file_file_id_seq', 12, true);


--
-- TOC entry 4874 (class 0 OID 0)
-- Dependencies: 225
-- Name: report_report_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.report_report_id_seq', 1, false);


--
-- TOC entry 4875 (class 0 OID 0)
-- Dependencies: 227
-- Name: user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_user_id_seq', 16, true);


--
-- TOC entry 4864 (class 0 OID 0)
-- Dependencies: 4863 4865
-- Data for Name: 35235..43451; Type: BLOBS; Schema: -; Owner: -
--

BEGIN;

SELECT pg_catalog.lo_open('35235', 131072);
SELECT pg_catalog.lowrite(0, '\x52656769737465726564207669612061646d696e2070616e656c');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35236', 131072);
SELECT pg_catalog.lowrite(0, '\x52656769737465726564207669612061646d696e2070616e656c');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35237', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35238', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35239', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35240', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35241', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35242', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35243', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35244', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35246', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35247', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35248', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35249', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35250', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35251', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35252', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35253', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35254', 131072);
SELECT pg_catalog.lowrite(0, '\x4173');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('35255', 131072);
SELECT pg_catalog.lowrite(0, '\x4173');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('43449', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('43450', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('43451', 131072);
SELECT pg_catalog.lowrite(0, '\x496d706f72746564206175746f6d61746963616c6c7920766961204a534f4e2061616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161612061616161616161616161616161616161616161616161');
SELECT pg_catalog.lo_close(0);

COMMIT;

--
-- TOC entry 4676 (class 2606 OID 35142)
-- Name: case case_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."case"
    ADD CONSTRAINT case_pkey PRIMARY KEY (numbercase);


--
-- TOC entry 4678 (class 2606 OID 35151)
-- Name: contact contact_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_pkey PRIMARY KEY (id_message);


--
-- TOC entry 4680 (class 2606 OID 35165)
-- Name: driver driver_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_email_key UNIQUE (email);


--
-- TOC entry 4682 (class 2606 OID 35163)
-- Name: driver driver_passport_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_passport_number_key UNIQUE (passport_number);


--
-- TOC entry 4684 (class 2606 OID 35161)
-- Name: driver driver_pesel_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_pesel_key UNIQUE (pesel);


--
-- TOC entry 4686 (class 2606 OID 35159)
-- Name: driver driver_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.driver
    ADD CONSTRAINT driver_pkey PRIMARY KEY (id_driver);


--
-- TOC entry 4688 (class 2606 OID 35174)
-- Name: file file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT file_pkey PRIMARY KEY (file_id);


--
-- TOC entry 4690 (class 2606 OID 35183)
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (report_id);


--
-- TOC entry 4692 (class 2606 OID 35194)
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- TOC entry 4694 (class 2606 OID 35192)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4696 (class 2606 OID 35199)
-- Name: vehicle vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_pkey PRIMARY KEY (plate_number);


--
-- TOC entry 4701 (class 2606 OID 35266)
-- Name: file created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT created_by FOREIGN KEY (user_id) REFERENCES public."user"(user_id) ON DELETE RESTRICT;


--
-- TOC entry 4704 (class 2606 OID 35230)
-- Name: vehicle fk11gt7sdj8cjtc3d8qggvjvgsy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT fk11gt7sdj8cjtc3d8qggvjvgsy FOREIGN KEY (id_driver) REFERENCES public.driver(id_driver);


--
-- TOC entry 4697 (class 2606 OID 35205)
-- Name: case fkagrh3iqta1y4excgn6ylbiaxa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."case"
    ADD CONSTRAINT fkagrh3iqta1y4excgn6ylbiaxa FOREIGN KEY (user_id) REFERENCES public."user"(user_id);


--
-- TOC entry 4700 (class 2606 OID 35215)
-- Name: contact fkcl15d6kk5ehp0bbpmg0csfxt7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT fkcl15d6kk5ehp0bbpmg0csfxt7 FOREIGN KEY (numbercase) REFERENCES public."case"(numbercase);


--
-- TOC entry 4702 (class 2606 OID 35220)
-- Name: file fkeu2q2o7d6ftfxedcd159ji7qt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file
    ADD CONSTRAINT fkeu2q2o7d6ftfxedcd159ji7qt FOREIGN KEY (numbercase) REFERENCES public."case"(numbercase);


--
-- TOC entry 4698 (class 2606 OID 35200)
-- Name: case fkl1gdva98978xt0xa0lvpjbph4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."case"
    ADD CONSTRAINT fkl1gdva98978xt0xa0lvpjbph4 FOREIGN KEY (id_driver) REFERENCES public.driver(id_driver);


--
-- TOC entry 4703 (class 2606 OID 35225)
-- Name: report fkmp90fgc7nkrk41o1cg0bxfj76; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT fkmp90fgc7nkrk41o1cg0bxfj76 FOREIGN KEY (generated_by) REFERENCES public."user"(user_id);


--
-- TOC entry 4699 (class 2606 OID 35210)
-- Name: case fkq49yjuhbu0n45r6vtasurb1dq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."case"
    ADD CONSTRAINT fkq49yjuhbu0n45r6vtasurb1dq FOREIGN KEY (plate_number) REFERENCES public.vehicle(plate_number);


-- Completed on 2026-08-03 18:05:18

--
-- PostgreSQL database dump complete
--

