spring.application.name=office-system
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=VARCHAR

server.port=${PORT}

# JWT Settings
jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Mailtrap
mailtrap.api-token=${MAILTRAP_API_TOKEN}
mailtrap.inbox-id=${MAILTRAP_INBOX_ID}
mailtrap.from-email=no-reply@officesystem.com


frontend.base-url=${FRONTEND_BASE_URL}

# PayU Sandbox
# PayU Sandbox
payu.sandbox.url=${APP_PAYU_SANDBOX_URL}
payu.client-id=${APP_PAYU_CLIENT_ID}
payu.client-secret=${APP_PAYU_CLIENT_SECRET}
payu.pos-id=${APP_PAYU_POS_ID}
payu.second-key=${APP_PAYU_SECOND_KEY}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

spring.jpa.open-in-view=false

spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=false
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=270000