spring.application.name=office-system
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/office_system}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:232365}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=VARCHAR

server.port=${PORT:8080}

# JWT Settings
jwt.secret=${JWT_SECRET:274d312f-e2e4-473c-ac3e-a9bde5f0c808}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=ea7c668d485e08
spring.mail.password=574edc58d3b8e5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayU Sandbox
# PayU Sandbox
payu.sandbox.url=${APP_PAYU_SANDBOX_URL:https://secure.snd.payu.com}
payu.client-id=${APP_PAYU_CLIENT_ID:516285}
payu.client-secret=${APP_PAYU_CLIENT_SECRET:e771aa4bd3d022bfec78b3c01ece73b4}
payu.pos-id=${APP_PAYU_POS_ID:516285}
payu.second-key=${APP_PAYU_SECOND_KEY:2f1de5bd3f83113716fe00a7b08996bb}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

spring.jpa.open-in-view=false

spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=false
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=270000